# Generated by Django 3.1.6 on 2021-02-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_store_key', models.CharField(max_length=200)),
                ('order_title', models.CharField(max_length=200)),
                ('order_number', models.IntegerField(default=1)),
                ('order_state_index', models.IntegerField(default=1)),
                ('order_rcv_time', models.DateTimeField(auto_now_add=True)),
                ('order_updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RobotState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_key', models.CharField(max_length=200)),
                ('robot_state_index', models.IntegerField(default=1)),
                ('robot_updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
