# Generated by Django 3.1.6 on 2021-02-16 15:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addorder',
            name='order_store_key',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=200),
        ),
    ]
